apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: istrays
  labels:
    app: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: istrays/users
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: users-configmap
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: db_user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: db_password
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: istrays
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  namespace: istrays
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: users-service
            port:
              number: 80