apiVersion: v1
kind: ConfigMap
metadata:
  name: users-migration
  namespace: istrays
data:
  V1_1__create_users.sql: |
    create table users (
      id serial primary key,
      name varchar not null,
      city varchar not null
    );